### ISSUE TITLE
BUG: Impossible to pay back full balance

### ISSUE THREAD

**Issue by velicanu** [makerdao/mcd-cdp-portal#283]
I think I found a bug.

Example:  in ETH-A Vault #6650 , the DAI debt is $102 but the button to pay back anything over $2.4 is grayed out. This is on oasis.app , see attached gif:

![oasis-bug](https://user-images.githubusercontent.com/5022772/96734709-cf570a00-1388-11eb-92b1-20ead7fa657f.gif)

**Comment by Padraic-O-Mhuiris** [comment]
Hey @velicanu, this is a preventative measure so that vaults are not able have a debt between 0 and the dust limit, the dust limit being 100 DAI in the case of ETH-A. The reason for this is that in the case of the vault being auctioned, it is not economical for the auction participants to bid on your collateral.

**Comment by velicanu** [comment]
Got it! So the only way to close this is to pay the full amount. Thanks for the info! Feel free to close this issue.
